name: Assume Aliyun Role and Print STS Token
on: [push]

jobs:
  assume-role:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Aliyun credentials
        id: configure-aliyun-credentials
        uses: aliyun/configure-aliyun-credentials-action@v1
        with:
          role-to-assume: 'acs:ram::1924794279035094:role/github-code-scan-1'
          oidc-provider-arn: 'acs:ram::1924794279035094:oidc-provider/githubcodescan'

      - name: Write STS Token to file
        run: |
          echo "${{ steps.configure-aliyun-credentials.outputs.aliyun-access-key-id }}" > access_key_id.txt
          echo "${{ steps.configure-aliyun-credentials.outputs.aliyun-access-key-secret }}" > access_key_secret.txt
          echo "${{ steps.configure-aliyun-credentials.outputs.aliyun-security-token }}" > security_token.txt

      - name: Display MD5 of STS Token parts
        run: |
          echo "Access Key ID MD5: $(md5sum access_key_id.txt | awk '{ print $1 }')"
          echo "Access Key Secret MD5: $(md5sum access_key_secret.txt | awk '{ print $1 }')"
          echo "Security Token MD5: $(md5sum security_token.txt | awk '{ print $1 }')"

      - name: Decode and print OIDC token
        run: |
          # 获取 OIDC 令牌
          OIDC_TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
          
          # 解析 OIDC 令牌的 payload 部分
          PAYLOAD=$(echo "$OIDC_TOKEN" | cut -d '.' -f 2 | base64 -d | jq .)
          
          # 打印 sub 和 aud 信息
          echo "OIDC Token sub: $(echo $PAYLOAD | jq -r .sub)"
          echo "OIDC Token aud: $(echo $PAYLOAD | jq -r .aud)"